name: Build Python Executables

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            artifact_name: calibrews-linux
            asset_name: calibrews-linux
          - os: windows-latest
            artifact_name: calibrews-windows.exe
            asset_name: calibrews-windows.exe
          - os: macos-latest
            artifact_name: calibrews-macos
            asset_name: calibrews-macos

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Build executable (Ubuntu/macOS)
      run: |
        pyinstaller --onefile --name ${{ matrix.artifact_name }} calibrews.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact_name }}
        path: |
          dist/${{ matrix.artifact_name }}
          dist/${{ matrix.artifact_name }}.exe

    - name: Upload to release
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: dist/${{ matrix.artifact_name }}${{ runner.os == 'Windows' && '.exe' || '' }}
        asset_name: ${{ matrix.asset_name }}
        asset_content_type: application/octet-stream
